# Code generated by c_to_python_font.py.
# Char set: 
# Cmd: ../micropython-font-to-py/c_to_python_font.py icons.txt close_font.py
version = '0.10'

def height():
    return 5

def baseline():
    return 5

def max_width():
    return 5

def hmap():
    return True

def reverse():
    return True

def monospaced():
    return False

def min_ch():
    return 65

def max_ch():
    return 64

_font =\
b'\x05\x00\x11\x0a\x04\x0a\x11'

_index =\
b'\x00\x00'

_mvfont = memoryview(_font)
_mvi = memoryview(_index)
ifb = lambda l : l[0] | (l[1] << 8)

def get_ch(ch):
    oc = ord(ch)
    ioff = 2 * (oc - 65 + 1) if oc >= 65 and oc <= 64 else 0
    doff = ifb(_mvi[ioff : ])
    width = ifb(_mvfont[doff : ])

    next_offs = doff + 2 + ((width - 1)//8 + 1) * 5
    return _mvfont[doff + 2:next_offs], 5, width
 
